version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: pentakill-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: pentakill-back
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - pentakill-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 5
      timeout: 3s

  backend:
    build: .
    container_name: pentakill-backend
    restart: always
    depends_on:
      - mysql
    environment:
      - DB_USER=root
      - DB_PASSWORD=123456
      - DB_HOST=pentakill-mysql
      - DB_PORT=3306
      - DB_NAME=pentakill-back
    networks:
      - pentakill-network

volumes:
  mysql_data:

networks:
  pentakill-network:
